### PR TITLE
Add SG & CoC that were removed by silly admin

### PR DESCRIPTION
**Pull request by nickmeinhold**
My bad, I changed history and screwed up the merge, in that these two files were removed... which is not cool.  I am 100% confident this gets us back to where we were but I will accept any punishment you deem appropriate, team.

### CODE REVIEW

**Comment by tamari-gray** [comment]
you know this means a dance video @nickmeinhold

**Review by tamari-gray — APPROVED** [review]
woop!

**Review by T-Davis — APPROVED** [review]
Good work!

**Comment by nickmeinhold** [comment]
Thanks heaps guys!

**Pull request merged**
